####Numpy provides a high-performance multidimensional array object, and tools for working with these arrays.It is the fundamental package for scientific computing with Python.

# Arrays in Numpy

#### Array in Numpy is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.In Numpy, number of dimensions of the array is called rank of the array.

In [ ]:
import numpy as np
#Creating a rank 1 Array
arr=np.array([1,2,3])
print(arr)
print(type(arr))

# Creating a rank 2 Array
arr1=np.array([[1,2,3],
              [4,5,6]])
print(arr1)

# Crating an array from tuple
arr3=np.array((1,2,3))
print(arr3)

[1 2 3]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
[1 2 3]


In [ ]:
# for dimensions element of each array have to fill
import numpy as np
list1=[[1,2,3],
      [4,5,6],
       [7,8,]]
arr1=np.array(list1)
print(arr1)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [ ]:
# Create a 2X3 array filled with zeros
zeros_array=np.zeros((2,3))
print(zeros_array)

#Create a 3X2 array filled with ones

Ones_array=np.ones((3,2))
print(Ones_array)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


Range of values

In [ ]:
range_arr=np.arange(10)
print("Range array:",range_arr)

range_arr = np.arange(2,10)
print("Range array:",range_arr)

range_arr =np.arange(0,10,2)
print("Range aray:",range_arr)

Range array: [0 1 2 3 4 5 6 7 8 9]
Range array: [2 3 4 5 6 7 8 9]
Range aray: [0 2 4 6 8]


Evenly spaced values

### numpy.linspace(start,stop,num=50,endpoint=True,dtupe=False)

In [ ]:
""" Why is it used?

To generate numbers at equal intervals within a specific range.

For plotting graphs, such as creating values for the X-axis or Y-axis.

In simulations in mathematics or physics.

To generate test or training data.""""




In [ ]:
# numpy.linspace(Start,stop,num=50,endpoint=True,dtupe=None,retstep=False)
import numpy as np
linespace_arr1= np.linspace(0,1,3, endpoint=False)  # 0-1 er moddhe 3 ta vag korci
print("Linespace array:",linespace_arr1)


linespace_arr2 = np.linspace(0,1,5,dtype=float,retstep=True)
print("Linspace array:",linespace_arr2)

Linespace array: [0.         0.33333333 0.66666667]
Linspace array: (array([0.  , 0.25, 0.5 , 0.75, 1.  ]), np.float64(0.25))


##  Reshaping and Transpose

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
arr.shape

(2, 3)

In [ ]:
arr=np.array([1,2,3,4,5,6])
print("Orginal array:\n",arr)
print("\n\n")
reshaped_arr=arr.reshape(2,3)  # 2 rows ,3 columns
print("Reshaped array:\n",reshaped_arr)
print("Shape:",reshaped_arr.shape)

Orginal array:
 [1 2 3 4 5 6]



Reshaped array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [ ]:
# Transpose a 2D array
arr=np.array([[1,2,3],[4,5,6]])
print("Orginal array:\n",arr)
print()
transpose_array=np.transpose(arr)
print("Transpose array:\n",transpose_array)

Orginal array:
 [[1 2 3]
 [4 5 6]]

Transpose array:
 [[1 4]
 [2 5]
 [3 6]]


Array Slicing and indexing

In [ ]:
arr=np.array([10,20,30,40,50])
print("First element:",arr[0])  # array indexing
print("Last element:",arr[-1])  # indexing
print("Element from index 1 to 3:",arr[1:4])  # Slicing


First element: 10
Last element: 50
Element from index 1 to 3: [20 30 40]


Concatanation,stacking and splitting

In [ ]:
# Concatenate two arrays along the first axis
array1=np.array([[1,2,],[3,4]])
array2=np.array([[5,6]])
print("Shapr:\n",array1)
print()
concatenate_arr=np.concatenate((array1,array2),axis=0)
print("concanete array:\n",concatenate_arr)


Shapr:
 [[1 2]
 [3 4]]

concanete array:
 [[1 2]
 [3 4]
 [5 6]]


In [ ]:
# concatenate two arrays along the first axis
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])
print(array2.shape)

concatenate_arr= np.concatenate((array1,array2),axis=1)
print(concatenate_arr)

(2, 2)
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Split an array into 3 equal parts
main_arr =np.array([1,2,3,4,5,6,])
split_arr=np.split(main_arr,3)
print(split_arr)
print()
arr1=split_arr[2]
print(arr1)

[array([1, 2]), array([3, 4]), array([5, 6])]

[5 6]


### In NumPy, stacking means joining multiple arrays together along a new axis (either vertically or horizontally).

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

# vertical and horizantal stacking

v_stack=np.vstack((arr1,arr2))
h_stack=np.hstack((arr1,arr2))
print("Vertical stack:\n",v_stack)
print("Horizantal stacking:\n",h_stack)

Vertical stack:
 [[1 2 3]
 [4 5 6]]
Horizantal stacking:
 [1 2 3 4 5 6]


Element-wise operation

In [ ]:
arr1 =np.array([1,2,3])
arr2=np.array([4,5,6])

print("Addition:",arr1+arr2)
print("Miltiplication:",arr1*arr2)
print("Squre of elements:",arr1**2)

Addition: [5 7 9]
Miltiplication: [ 4 10 18]
Squre of elements: [1 4 9]


Arithmatic and Statistical Operations

In [ ]:
# Compute the sum of array elements
print(v_stack)
print()
sum_value=np.sum(v_stack)
print(sum_value)

[[1 2 3]
 [4 5 6]]

21


In [ ]:
# Compute the mean of array elements           Mean=  Sum of all values/Number of values
mean_value =np.mean(v_stack)
print(mean_value)

3.5


In [ ]:
# Compute the standard deviation
                                       #The standard deviation (SD) is a measure of how spread out the numbers in a dataset are from the mean (average).


std_value = np.std(v_stack)
print(std_value)

1.707825127659933


In [ ]:
# Compute the median of array elements
                                      #The median is the middle value of a set of numbers when they are arranged in order (ascending or descending).
                                      # It separates the higher half from the lower half.
array=np.array([1,3,5,4])
median_value =np.median(array)
print(median_value)

3.5


In [ ]:
# Find the minimum value in the array
array=np.array([5,3,2,1,4])
min_value=np.min(array)
print(min_value)
print()

# Find the maximum value in the array
max_value=np.max(array)
print(max_value)

1

5


Random Number generation

In [ ]:
# Generate a 2X2 array of random bumbers uniformaly distributed over (0,1)
random_array=np.random.rand(2,2)
print(random_array)

[[0.65256031 0.84048529]
 [0.87803733 0.97450532]]


In [ ]:
# Generate a single random number from the standerd normal distribution
single_value = np.random.randn()
print(single_value)

-0.493012623312632


In [ ]:
# Generate a 2X3 array numbers from a standard normal distribution

random_normal_array=np.random.randn(2,2)
print(random_normal_array)

[[ 0.56551499 -0.89084518]
 [ 0.08413155 -0.16560912]]


In [ ]:
# Generate random integers between 0 and 10 (exxlusive)
random_integers= np.random.randint(0,10,size=(2,3))
print(random_integers)

[[7 0 9]
 [2 7 7]]


# Broadcasting

In [ ]:
 #Broadcasting in NumPy is a feature that allows array operations between arrays of different shapes.

arr5 =np.array([1,2,3])
arr6 =np.array([[1],[2],[3]])


result =arr5+arr6   # Broadcasts arr1 across arr2
print("Broadcasted addition:\n",result)


Broadcasted addition:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
result=arr5-arr6
print(result)

[[ 0  1  2]
 [-1  0  1]
 [-2 -1  0]]


# Linear Algebra Operation

In [ ]:
matrix =np.array([[1,2],[3,4]])

# Martrix inverse
inv_matrix =np.linalg.inv(matrix)
print("Inverse of matrix:\n",inv_matrix)

Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# Matrix determinant
det_matrix =np.linalg.det(matrix)
print("Determinat of matrix:",det_matrix)

Determinat of matrix: -2.0000000000000004


In [ ]:
# Eigenvalues and Eigenvectors
eigenvalues,eigenvectors=np.linalg.eig(matrix)
print("Eigenvalues:",eigenvalues)
print("Eigenvectoes:\n ",eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectoes:
  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
# Find the index of the minimum value
array =np.array([5,3,2,4])
argmin_index =np.argmin(array)
print(argmin_index)

2


In [ ]:
# Find the index of the maximum value
array = np.array([5, 3, 2, 1, 4])
argmax_index = np.argmax(array)
print(argmax_index)                    #index value

0


In [ ]:
# Find indices where the condition is met
array = np.array([1, 2, 3, 4, 5])
indices = np.where(array > 3)
print(indices)

(array([3, 4]),)
